import "./globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import Topbar from "../components/navbar";
import Providers from "./providers";
import Terminal from "../components/terminal";

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swapnil's | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto_mono.className}>
      <body className="antialiased min-h-screen">
        <Providers>
          <div className="flex flex-col container pt-8">
            <Topbar />
            <main className="mb-8">{children}</main>
            <Terminal />
          </div>
        </Providers>
      </body>
    </html>
  );
}
